### ISSUE TITLE
Use Case: Add a plant

### ISSUE THREAD

**Issue by souvorinkg** [DiscoTrayStudios/iseegreen#1]
I searched up "Aloe Vera," a popular plant, known in 95 languages. I didn't see the plant in the DB. It would be great if I could add it from the site!
<img width="997" alt="image" src="https://github.com/user-attachments/assets/d0292c86-e87f-4e55-94ec-a2dd6dcb0c65">

**Comment by reidst** [comment]
_Aloe vera_ is in the database, with Kew ID 530017-1.

I'm not sure allowing users to add plants to the database was one of the use cases the client wanted, so this issue should be suspended until we get further clarification from them (and closed if they decide against it).
